student_name = input("Student name: ")
student_id = input("Student ID: ")
department = input("Department: ")
year = input("Year: ")
university = input("University: ")
phone = input("Phone number: ")

print()
print("+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print(f"| Name: {student_name:<24}|")
print(f"| ID: {student_id:<26}|")
print(f"| Department: {department:<19}|")
print(f"| Year: {year:<26}|")
print(f"| University: {university:<19}|")
print(f"| Phone: {phone:<23}|")
print("+--------------------------------+")