name=input("enter your name: ")
weight=float(input("enter your weight in kg: "))
height=float(input("enter your height in m: "))
BMI=weight/(height**2)
print(f"==============================\n BMI REPORT \n ======================================== \n Name: {name} \n Weight: {weight} kg \n Height: {height} m \n BMI: {BMI} \n ========================================")