print("=" * 40)
print("       STUDENT INTRODUCTION")
print("=" * 40)

full_name = input("Full name: ")
age = input("Age: ")
city = input("City: ")
university = input("University: ")
department = input("Department: ")
favorite_language = input("Favorite programming language: ")
programming_goal = input("One programming goal: ")

print()
print(f"My name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {favorite_language}.")

print()
print("My programming goal:")
print(programming_goal)

print()
print("=" * 40)